name: Jest and e2e tests
on: [push]

jobs:
  build:
    name: Run Jest and Testcafe tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v1
      - name: Install modules
        run: yarn
      - name: Run jest tests
        run: yarn test
      - name: build app
        run: yarn build
      - name: Run testcafe tests
        run: yarn test:e2e
